### ISSUE TITLE
按照步骤安装后报错 Cannot find module 'webpack'

### ISSUE THREAD

**Issue by stjava** [eolinker/eoapi-remote-server#2]
![image](https://user-images.githubusercontent.com/20898173/178644155-4914f6b5-d79b-407b-83ec-b59ef29a324c.png)

**Comment by stjava** [comment]
然后执行命令后 npm install --save-dev webpack,可以启动了，但是启动报错

![image](https://user-images.githubusercontent.com/20898173/178644589-4f03e077-16df-4322-ad39-c8aadbe2fc01.png)

**Comment by scarqin** [comment]
@stjava 你的 Node 版本是？

**Comment by stjava** [comment]
> @stjava 你的 Node 版本是？

16.16.0

**Comment by scarqin** [comment]
@stjava 我重新 clone 了无法复现，请按照一下步骤试试：
1. 删除数据库
2. 重建数据库
3. 重新 npm start

**Comment by stjava** [comment]
是的，我是新建了数据库，然后 npm ci 安装的，
删除重新建，还是这个问题。 重新建数据库，我需要手动导入表吗？

**Comment by stjava** [comment]
![image](https://user-images.githubusercontent.com/20898173/178666482-4ebc3b38-0644-4926-84b8-6200690952c2.png)

而且看数据库，表是已经建立了的

**Comment by scarqin** [comment]
@stjava ok,我是用 yarn 安装的，我试试 npm。
你可以试试用 yarn，我估计是依赖问题，我先用 npm 复现看看，解决了告诉你，后续我们会考虑用 yarn 优化安装体验

**Comment by stjava** [comment]
嗯嗯，主要是文档里面也是 npm,我是照着来的

**Comment by stjava** [comment]
yarn 也是一样的问题

**Comment by scarqin** [comment]
@stjava 方便的话留一下你的向日葵 ID 我远程看下

**Comment by scarqin** [comment]
@stjava 可以删除一下 dist 试试

**Comment by scarqin** [comment]
@stjava 我们使用 docker 安装解决了依赖问题，可以试试
