### ISSUE TITLE
feat: Dockerfile自定义mysql主机名和端口

### ISSUE THREAD

**Issue by ChingCdesu** [eolinker/eoapi-remote-server#20]
./wait-for-it.sh中的参数能不能使用ENV传入的mysql主机名和端口
在k8s中部署镜像会有问题
k8s的主机名规范是`<service-name>.<namespace>.svc`
eg: `mysql.database.svc`

**Comment by ChingCdesu** [comment]
追加一条：configuration.ts中为啥是MYSQL_ROOT_PASSWORD, 和eoapi本身的不同，我在部署的时候一直Access Denied，后面发发现环境变量和eoapi本身的镜像不同

**Comment by scarqin** [comment]
@ChingCdesu 好，我们看下。
@buqiyuan 跟进一下这个 issue～

**Comment by buqiyuan** [comment]
感谢反馈，已修正
