### ISSUE TITLE
eoapi-remote-server exited with code 1

### ISSUE THREAD

**Issue by suiyueou** [eolinker/eoapi-remote-server#24]
![image](https://user-images.githubusercontent.com/48700331/204463776-a8bdaeaf-ee66-4242-8faa-c78ab3cdf16d.png)

如图和标题所示，我是克隆仓库后直接 docker compose up 运行，未修改任何配置。

**Comment by scarqin** [comment]
![image](https://user-images.githubusercontent.com/15225835/204464311-6b22d3e1-d376-4473-994f-50a7267253ce.png)
@suiyueou 确认一下步骤是否和文档一致
https://docs.eoapi.io/docs/storage.html#%E6%9C%8D%E5%8A%A1%E8%BF%90%E8%A1%8C

**Comment by suiyueou** [comment]
> ![image](https://user-images.githubusercontent.com/15225835/204464311-6b22d3e1-d376-4473-994f-50a7267253ce.png) @suiyueou 确认一下步骤是否和文档一致 https://docs.eoapi.io/docs/storage.html#%E6%9C%8D%E5%8A%A1%E8%BF%90%E8%A1%8C

额，刚刚没看到这一步，这是需要手动创建嘛？

**Comment by scarqin** [comment]
@suiyueou 是的，暂时没有自动创建，因为可能需要用自己的数据库。

**Comment by suiyueou** [comment]
> @suiyueou 是的，暂时没有自动创建，因为可能需要用自己的数据库。

那这一步的文档可否稍微详细点，或者我应该如何操作（？

**Comment by scarqin** [comment]
教程：
https://www.runoob.com/mysql/mysql-create-database.html
数据库信息看配置：
![image](https://user-images.githubusercontent.com/15225835/204518208-39de9d03-cca7-4d95-bb5f-ff3aeee47aca.png)

**Comment by suiyueou** [comment]
> 教程： https://www.runoob.com/mysql/mysql-create-database.html 数据库信息看配置： ![image](https://user-images.githubusercontent.com/15225835/204518208-39de9d03-cca7-4d95-bb5f-ff3aeee47aca.png)

![image](https://user-images.githubusercontent.com/48700331/204535316-3da6bb11-4cae-4d73-80e5-82227430d853.png)

是这个吗？自动生成的，但是空空的。

**Comment by scarqin** [comment]
@suiyueou 对，然后按照步骤来。
![image](https://user-images.githubusercontent.com/15225835/204536963-66b90545-4325-4181-827e-0947b9a9029a.png)
如果没有启动成功看下 FAQ，FAQ 没提到的话，根据 2 截图一下 Docker 报错
![image](https://user-images.githubusercontent.com/15225835/204537088-c534042c-702a-46ab-8be2-9087723a9d4c.png)

**Comment by suiyueou** [comment]
未能启动成功，这是日志：

![image](https://user-images.githubusercontent.com/48700331/204541217-cd1f54f6-d649-4c6c-afdb-c98fcd3b6011.png)


![image](https://user-images.githubusercontent.com/48700331/204541202-610f62c8-47d0-40f5-96d5-aaddcb97f84e.png)

**Comment by scarqin** [comment]
@suiyueou 看日志是启动成功了，服务器是否有防火墙、安全组之类的？

**Comment by suiyueou** [comment]
> @suiyueou 看日志是启动成功了，服务器是否有防火墙、安全组之类的？

端口组是开放了的

**Comment by suiyueou** [comment]
> @suiyueou 看日志是启动成功了，服务器是否有防火墙、安全组之类的？

不好意思，是我给 eoapi 的 nginx.conf 文件 volumes 映射注释给取消了，导致了无法访问，现在访问已经正常了。

但是远程服务依旧还是老样子报错。

**Comment by scarqin** [comment]
@suiyueou 你加 q 群：981965807 吧，我远程看看
