### ISSUE TITLE
启动服务报错，对应的路径不存在

### ISSUE THREAD

**Issue by declandragon** [eolinker/eoapi-remote-server#4]
操作步骤
* git clone
* npm i
* 修改 src/config/config.development.ts 配置
* npm run start
* 然后就会报下面这个错误

![image](https://user-images.githubusercontent.com/37643710/180985972-ed30261a-a9ea-45d8-b3e9-a5fd0796e028.png)

环境信息
* win10
* node 
```
PS C:\wnmp\www\local\test-0726> node -v
v16.14.2
```

**Comment by scarqin** [comment]
@declandragon 如果不用 docker 的话，用 yarn 安装，记得删库+重新 clone 部署 👴

**Comment by declandragon** [comment]
删除所有文件，清空数据库，重新clone，问题依然复现 😭 

操作步骤：
* git clone 
* 修改 src/config/config.development.ts 配置
* yarn
* yarn start:dev

![image](https://user-images.githubusercontent.com/37643710/181151011-2845bb52-1120-488a-9553-c6d3afbe7d17.png)

环境信息

* win10
* node 16 
* yarn
```
PS C:\wnmp\www\local\test-0726> yarn -v
1.22.19
```

**Comment by scarqin** [comment]
@declandragon 你可以使用 docker 吗？不能的话只能远程：1054139596 看看情况了，环境问题比较难复线

**Comment by declandragon** [comment]
感谢回复，使用 docker 可以正常运行
