### ISSUE TITLE
能出一个官方Docker镜像吗

### ISSUE THREAD

**Issue by huluohu** [eolinker/eoapi-remote-server#6]
希望官方能出一个docker镜像，谢谢

**Comment by scarqin** [comment]
@huluohu 好的，我们考虑下

**Comment by huluohu** [comment]
> @huluohu 好的，我们考虑下

谢谢

**Comment by buqiyuan** [comment]
已经发布的[dockerhub](https://hub.docker.com/repository/docker/eolinker/eoapi-remote-server/tags?page=1&ordering=last_updated)了，欢迎使用
