### ISSUE TITLE
ReadMe 文档 看着太恼火了 

### ISSUE THREAD

**Issue by van-chin** [eolinker/eoapi-remote-server#7]
看完 部署文档 感觉太不明了了 

一会是在本地 yarn

一会儿是 要用docker 

是要结合起来么

希望能重新调整一下 文档，方便能看懂部署

**Comment by scarqin** [comment]
@van-chin 息怒息怒，正在调整，已自我批评

**Comment by van-chin** [comment]
@scarqin 非常感谢！
