### ISSUE TITLE
api 文档可以加个swagger嘛？或者对API的设计文档有没有在哪可以体现的？

### ISSUE THREAD

**Issue by liujunzheng** [eolinker/eoapi-remote-server#9]

**Comment by scarqin** [comment]
https://www.eolink.com/share/index?shareCode=ZLadDH

**Comment by liujunzheng** [comment]
@scarqin 好的，谢谢，你这响应也太及时了。

**Comment by scarqin** [comment]
@liujunzheng Spider-Man - Hanging on the Internet every day

**Comment by liujunzheng** [comment]
@scarqin 我刚大致看了一遍这个项目，目前这个API端只是用来做存储用的，是哈？然后具体发起请求，是在客户端，然后把结果啥的存起来，那么问一下，后期会不会有调整为：发起请求是在API端处理？还是说就是这样的架构设计，该项目。

**Comment by scarqin** [comment]
1. 是的
2. 已经支持，但是不推荐。因为无法本地请求，而且我们的桌面端希望可以无需部署单机使用的

我们的 [live demo](https://eoapi.io/) 就是用 serverless api 发起请求的，感兴趣可以看看：https://juejin.cn/post/7091915907248685070

Node 发起请求的服务在：https://github.com/eolinker/eoapi/tree/main/src/workbench/node/server
<img width="820" alt="image" src="https://user-images.githubusercontent.com/15225835/184333812-3c0f60dd-d94c-4e31-9e4d-1f55551aedd9.png">

**Comment by liujunzheng** [comment]
明白了，之前没理解设计的原因是啥，client端之前看到，有你上面发的nodejs，也有使用electron新开进程发请求的两种方式，现在明白为啥这么设计了，脱机+持久化，两者既可以分离也可以兼得，按需所取。

**Comment by liujunzheng** [comment]
再问一个，后期这个开源版本，会不会加用户和团队协作功能？这个感觉应该不太会，毕竟还有官方产品在。

**Comment by scarqin** [comment]
@liujunzheng 远程数据源是协作的第一步，暂时不会做得很深。
不是因为官方产品，是因为我们开源工具的核心是插件生态，所以精力会优先放在插件上。

**Comment by liujunzheng** [comment]
@scarqin OK~，了解了，Thanks♪(･ω･)ﾉ
